### ISSUE TITLE
Make an English version of the site

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-comparator#102]

**Comment by askorutin26** [comment]
Здравствуйте. Попытался сделать, и в целом все получилось, но есть вопросы. Перевод профессий стоит сделать? Сейчас через yml файл работает, вынести это в locales? Ну и предыдущий issues видел, страница со школами тоже не работает пока.

**Comment by ashikov** [comment]
@seth2810 не совсем уверен, но можешь ли ты ответить на вопросы?)

**Comment by seth2810** [comment]
@askorutin26 тут без произвольного кода не обойдется. Смотри как делал я, когда в hexlet.guides была похожая задача с постами:

- все страницы с переводами разделяем по локалям и кладем в [отдельную папку](https://github.com/Hexlet/hexletguides.github.io/tree/main/next-app/data/posts) в `data`;
-  дальше есть какой-то [код](https://github.com/Hexlet/hexletguides.github.io/blob/main/next-app/api/index.js#L38), который получает список в зависимости от локали;
- а уже конкретно на странице извлекается нужный item или объект, в твоем случае профессия, которую мы [пробрасываем](https://github.com/Hexlet/hexletguides.github.io/blob/main/next-app/pages/%5Bname%5D.js#L33) через `getStaticProps`

**Comment by seth2810** [comment]
Ну или еще вариант, пойти как в предыдущем issue и делать два ключа под каждую локаль, что кмк выглядит весьма "костыльно", и при росте локалей будет стрелять нам в ногу.

**Comment by askorutin26** [comment]
@seth2810 Спасибо за помощь! Буду пробовать.

**Comment by ashikov** [comment]
Передумали делать
