### ISSUE TITLE
Добавить редирект с http на https

### ISSUE THREAD

**Issue by ashikov** [Hexlet/hexlet-comparator#108]
Сейчас сайт можно открыть по ссылке http://schools.hexlet.io/ и он будет работать, как ни в чём не бывало. Так быть не должно. 

Нужно сделать 301 редирект, если происходит обращение по http, на https. Поведение должно быть, как, например, у hexlet.io:

```bash
$ curl -IS http://hexlet.io 
HTTP/1.1 301 Moved Permanently
Location: https://hexlet.io/
# ...
# какие-то ещё заголовки
```

**Comment by askorutin26** [comment]
Попробовал сделать, pr отправил

**Comment by askorutin26** [comment]
получилось запретить использовать http браузером, не уверен что это то, что нужно, там max-age установлен: 
```
const securityHeaders = [{
  key: 'Strict-Transport-Security',
  value: 'max-age=63072000; includeSubDomains; preload'
},]
```
задеплоил, работает : https://thawing-ridge-38780.herokuapp.com/

Пытался сделать редирект через middleware, на heroku выдает ошибку о слишком частом перенаправлении, локально перенаправляет, но не отрывается - This site can’t provide a secure connection
