### ISSUE TITLE
Feature request: Устранить дублирование 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-comparator#136]
### Problem description

Сейчас страница строится в соответствии очерёдностью выбора пользователя, потому не исключены вот такие ситуации: 
https://schools.hexlet.io/professions/frontend-developer/competitors/avenue-vs-geekbrains

https://schools.hexlet.io/professions/frontend-developer/competitors/geekbrains-vs-avenue

### Proposed solution

Устранить дублирование

**Comment by EvSedov** [comment]
Беру в работу.

**Comment by EvSedov** [comment]
Сделано.
