### ISSUE TITLE
Feature request: Добавить тег rel canonical 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-comparator#137]
### Problem description

Нужно настроить подстановку тега rel canonical на все страницы сайта. В значение тега нужно подставлять адрес текущей открытой страницы. Подстановка должна происходить без учета всех возможных параметров в URL страницы.
Подробнее: https://yandex.ru/support/webmaster/robot-workings/canonical.html

Пример https://schools.hexlet.io/professions/frontend-developer?from=yandex
Канонический адрес https://schools.hexlet.io/professions/frontend-developer 

### Proposed solution

-

**Comment by EvSedov** [comment]
@fey сделано
