### ISSUE TITLE
Feature request: Добавить название профессии в заголовок на страницу сравнения школ 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-comparator#138]
### Problem description

На странице сравнения профессий разных школ, в заголовок h1, нужно добавить название профессии 
![image](https://user-images.githubusercontent.com/77053797/216355421-ac057e0b-a157-4625-ba1c-2f9c0688adf1.png)

Шаблон заголовка: Сравниваю профессию [название профессии] в школах [название1] и [название2]

### Proposed solution

Добавить название профессии в заголовок на страницу сравнения школ

**Comment by seregad544** [comment]
взял задачу

**Comment by ssssank** [comment]
Закрыто #144
