### ISSUE TITLE
Feature request: Добавить “хлебные крошки” на сайт 

### ISSUE THREAD

**Issue by acidmaksim** [Hexlet/hexlet-comparator#140]
### Problem description

Хлебные крошки – цепочка ссылок, указывающая полный путь от главной страницы, до страницы, открытой в данный момент. Последний элемент цепочки должен выводиться без активной ссылки. \

### Proposed solution

Нужно реализовать хлебные крошки на всех страницах кроме главной. Должны выводиться в верхней части страницы, между шапкой и заголовком.
![image](https://user-images.githubusercontent.com/77053797/216357297-a0a5d111-8c32-4b9a-b8e8-553ab902204f.png)

**Comment by IvanMogilevskiy** [comment]
Я возьму в работу, если вы не против.

**Comment by EvSedov** [comment]
Тоже возьму в работу, кто первый, того и тапки =)

**Comment by fey** [comment]
@EvSedov а тут что еще у нас осталось?

**Comment by EvSedov** [comment]
@fey "хлебные крошки" на сайт добавили, осталось добавить перевод "хлебных крошек" на русский язык.

**Comment by EvSedov** [comment]
@fey давай данное issue закроем как выполненное. 

Для перевода "хлебных крошек" на русский язык я сделал отдельное [issue](https://github.com/Hexlet/hexlet-comparator/issues/159).

**Comment by fey** [comment]
Ага. 
https://github.com/Hexlet/hexlet-comparator/pull/151
