### ISSUE TITLE
Поправить верстку карточек школ

### ISSUE THREAD

**Issue by EvSedov** [Hexlet/hexlet-comparator#157]
### Problem description

![image](https://user-images.githubusercontent.com/29833092/227791463-e7c94f2c-974f-42c4-8999-9513fbb41f36.png)

На мобильных устройствах при просмотре карточек школ названия школ и кнопки выходят за пределы карточки. 

### Proposed solution

Необходимо поправить верстку.

**Comment by Dmitriy-SP** [comment]
Добрый день! Беру, если свободно.
