### ISSUE TITLE
Добавить для "хлебных крошек" перевод на русский язык.

### ISSUE THREAD

**Issue by EvSedov** [Hexlet/hexlet-comparator#159]
### Problem description

На сайте "хлебные крошки" должны отображаться на русском языке.

"Хлебные крошки" – цепочка ссылок, указывающая полный путь от главной страницы, до страницы, открытой в данный момент.

### Proposed solution

Добавить для "хлебных крошек" перевод на русский язык.

**Comment by artch3r** [comment]
Попробую реализовать. Беру в работу.
