### ISSUE TITLE
Внести мета-теги

### ISSUE THREAD

**Issue by ArthurCher** [Hexlet/hexlet-comparator#162]
### Problem description

На страницы школ проекта https://schools.hexlet.io/ нужно внести мета-теги согласно файлу ниже:

https://docs.google.com/spreadsheets/d/1stjgQsXN-b9ZkP8c51vAEL2WXNKAfR8D7sScVWP55Vo/edit?usp=sharing

### Proposed solution

Внести title, description

**Comment by redaktorscha** [comment]
Привет! Это же в locales поправить нужно? Я могу взять.
