### ISSUE TITLE
сделать страницу "о проекте"

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-comparator#31]
нужно создать страницу "о проекте", по аналогии с  https://cv.hexlet.io/pages/about

**О проекте**

Hexlet Comparator - это проект с открытым исходным кодом, созданный и поддерживаемый сообществом Hexlet.
Присоединяйтесь к сообществу, публикуйте резюме и оставляйте рекомендации другим участникам. Расскажите о сайте коллегам и друзьям!
Исходный код платформы Hexlet Comparator доступен на GitHub. Вы можете поучаствовать в процессе разработки.

[Исходный код](https://github.com/Hexlet/hexlet-comparator)

**Comment by boldurean** [comment]
Тут так же https://github.com/Hexlet/hexlet-comparator/commit/226d9d27a11273897bea2b86aa781ee234ff9c14
