### ISSUE TITLE
сделать подвал для сайта 

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-comparator#32]
нужно сделать такой же подвал как на CV только обновить ссылки на страницу "о проекте" и на репозиторий 
страница о проекте - [здесь ](https://github.com/Hexlet/hexlet-comparator/issues/31)
ссылка на репозиторий https://github.com/Hexlet/hexlet-comparator

**Comment by boldurean** [comment]
Подвал готов вроде, пора закрывать https://github.com/Hexlet/hexlet-comparator/pull/35/commits/226d9d27a11273897bea2b86aa781ee234ff9c14
