### ISSUE TITLE
Задать метатеги

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-comparator#34]
**страница списка профессий** 
https://schools.hexlet.io/professions
title: Cравнение онлайн курсов по программированию
description: Онлайн сервис для сравнения курсов по программированию от разных школ. Cравнение онлайн курсов по программированию - Hexlet Comparator 

**страница конкретной профессии** 
https://schools.hexlet.io/professions/[:id]
title: [название профессии] – сравнение курсов онлайн-школ
description: Обзор курсов по профессии [название профессии] в популярных онлайн-школах- Hexlet Comparator 

**страница школы**
https://schools.hexlet.io/schools/[:id]
title: [название школы]: профессии, курсы, обучение в [название школы]
description: Обзор курсов от [название школы].  Какие профессии есть в [название школы], обзор и сравнение онлайн школы

**страница сравнения**
https://schools.hexlet.io/professions/[:id]/competitors/[:id-1]-vs-[:id-2]
title: [название профессии]: сравнение [название школы 1] и [название школы 2], что лучше 
description: Сравнение курсов по профессии [название профессии] в онлайн-школах [название школы 1] и [название школы 2]. Куда пойти учиться по профессии [название профессии]

**Comment by danilaprokoshev** [comment]
Взял в работу.
Планирую добавить метатеги для двух существующих локалей (ru и en).
