### ISSUE TITLE
Не работает en локаль

### ISSUE THREAD

**Issue by boldurean** [Hexlet/hexlet-comparator#39]
https://i.imgur.com/VXCDVuS.png

**Comment by bondiano** [comment]
А почему она должна именно через роутер работать?

**Comment by boldurean** [comment]
У меня по дефолту в хроме открывается с путями en https://i.imgur.com/54kGtzj.png причем стартовая страница открывается а дальше не пашет.

**Comment by mokevnin** [comment]
Хм, английской локали не должно быть в принципе. Удалил.
