### ISSUE TITLE
Add a table with a description of the school

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-comparator#48]
На странице школы, нужно добавить таблицу с описанием. Таблица с описанием нужна вот здесь http://joxi.ru/GrqgN8LukNnlE2 
Список полей с примерами заполнения есть здесь https://docs.google.com/document/d/1oGvevvAruSzPbP3kU6lx1s0YJ7ND6jF5VKlR4zq-khQ/edit?usp=sharing

Нужна таблица с подзаголовками, как в примере (в доке). Логика вывода: если какое то поле за полнено, то строку в таблице не выводить. 

Дополнительно, нужно в шапку страницы добавить кнопку с якорной ссылкой "Описание" со ссылкой на таблицу 
вот здесь  http://joxi.ru/8AnVy16I7q1EWA
Кнопку со ссылкой на описание установить первой (перед профессиями). 

Для тестирования можно использовать нашу страницу https://schools.hexlet.io/schools/hexlet
Для теста можно взять весь контент из доке (для проверки нужна полностью заполненная таблица со всеми выведенными строками)

**Comment by acidmaksim** [comment]
@prio65 половина ссылок не работает

**Comment by ssssank** [comment]
@fey предлагаю закрыть
