### ISSUE TITLE
добавить новые поля в описание профессий 

### ISSUE THREAD

**Issue by prio65** [Hexlet/hexlet-comparator#49]
Обновить поля описания профессий. Добавить новые поля и заполнить полностью одну профессию для примера.  

Полный список после с примерами значений есть здесь https://docs.google.com/document/d/1DJhrK7t9TXV1rV0B4wjG5E3O-kDeYOwzZHBGgY4HyTc/edit?usp=sharing

В этом же доке есть тестовый контент для курса Python-разработчик (хекслет) - https://github.com/Hexlet/hexlet-comparator/blob/main/data/schools/hexlet.yml

**Comment by acidmaksim** [comment]
@prio65 ссылка на гугл док не работает

**Comment by ssssank** [comment]
@fey предлагаю закрыть
