### ISSUE TITLE
Поправить описания школ

### ISSUE THREAD

**Issue by Malcom1986** [Hexlet/hexlet-comparator#69]
Сейчас на страницах школ (https://schools.hexlet.io/schools/hexlet) заголовки отображаются в таком виде: `school.descriptions.info`, `school.professions`

**Comment by elisad5791** [comment]
Я сейчас разбиваю большой пуллреквест viklm на части. Там есть эта правка. Только что отправила пуллреквест с ней.

**Comment by ashikov** [comment]
@Malcom1986 Я так понимаю эта история уже исправлена? Могу закрывать PR?

**Comment by senigius** [comment]
@ashikov в моём последнем пиаре я задеплоил, всё работает на проде, можно проверить
Так что надо бы закрыть и передеплоить

Как удостоверитесь, сниму с heroku деплой, а то я забыл

**Comment by fey** [comment]
посмотрите как щас на проде. Если ок - смержим :thinking:

**Comment by ashikov** [comment]
А [вот тут](https://schools.hexlet.io/schools/hexlet) school.descriptions.info потому, что не заполнено описание? Заголовки нормально отображаются.

**Comment by fey** [comment]
ну, ишшус выглядит все еще актуальным.

**Comment by senigius** [comment]
Так прод не перезапускался с 8 марта же

**Comment by senigius** [comment]
Другое дело, но теперь на странице /schools вроде что-то по-другому стало
Логотипы пропали или мне кажется?

**Comment by fey** [comment]
А покажи скрин

**Comment by senigius** [comment]
![image](https://user-images.githubusercontent.com/98415831/173029052-cb159f5a-15cb-45ff-814f-a1f3d2560425.png)
Я про это, я просто не помню как было

**Comment by fey** [comment]
По-моему раньше так и было. Но можно туда лого добавить.
В принципе этот ишшус закрываю
