### ISSUE TITLE
2. Добавить школу Бруноям

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-comparator#85]

**Comment by Nesaq** [comment]
Беру в работу.

**Comment by ashikov** [comment]
Получается?

**Comment by Nesaq** [comment]
Привет. Я в принципе понял, что именно надо делать. Завтра примусь за работу. Спасибо, что спросили!

**Comment by Nesaq** [comment]
@ashikov Привет! Отправил ПР.  Правда не пойму тот ли номер issue указал в коммите
