### ISSUE TITLE
5. Добавить школу Нетология

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-comparator#88]

**Comment by Idzanaagi** [comment]
@fey привет, я правильно понимаю, что нужен yml по аналогии с лежащими в data/schools?

**Comment by ashikov** [comment]
@Idzanaagi да, верно. Еще нужны будут ассеты, вот тут можно глянуть пример: https://github.com/Hexlet/hexlet-comparator/tree/main/public/assets/schools/hexlet

**Comment by Idzanaagi** [comment]
@ashikov поняла, спасибо

**Comment by ashikov** [comment]
@Idzanaagi как успехи? 🙂

**Comment by Idzanaagi** [comment]
@ashikov на финишной прямой, завтра-послезавтра сдам)

**Comment by Idzanaagi** [comment]
@ashikov привет, пара уточнений: 
В открытой информации нашла только количество часов теории и практики, но не уроков. Кинуть им запрос или как поступить? И еще. Там есть, например, профессии сисадмина, разработчика на Unity, sql-разработчика или bitrix-разработчика. Это тоже всё надо?

**Comment by fey** [comment]
@Idzanaagi привет, давай добавим то, что есть. А по остальным профессиям пока не надо.

**Comment by Idzanaagi** [comment]
@ashikov а насчет часов/уроков?

**Comment by fey** [comment]
Просто укажите то, что сейчас доступно, постепенно можно будет внести недостающие данные :)

**Comment by Idzanaagi** [comment]
ок, спасибо

**Comment by Idzanaagi** [comment]
@fey ПР вроде ушёл
