### ISSUE TITLE
7. Добавить школу ShultaisEducation

### ISSUE THREAD

**Issue by fey** [Hexlet/hexlet-comparator#90]

**Comment by Aleksandr-Bondarev** [comment]
Добрый день! Беру в работу

**Comment by ashikov** [comment]
@Aleksandr-Bondarev как успехи с добавлением школы? Если есть трудности, спрашивайте, мы поможем.

**Comment by Aleksandr-Bondarev** [comment]
> @Aleksandr-Bondarev как успехи с добавлением школы? Если есть трудности, спрашивайте, мы поможем.

сделал pr, надеюсь все так)

**Comment by fey** [comment]
а у вас локально на компе сборка проходит?

**Comment by Aleksandr-Bondarev** [comment]
увы, локально аналогичная история
